logstashPipeline:
  app.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      json {
        source => "message"
        skip_on_invalid_json => true
        add_tag => ["json_filter"]
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "logstash"
      }
    }
service:
    annotations: {}
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      - name: beats
        port: 5044
        protocol: TCP
        targetPort: 5044
      - name: http
        port: 9600
        protocol: TCP
        targetPort: 9600

labels:
  app.kubernetes.io/component: logstash
