daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            include_annotations: ["isModel", "model", "modelVersion", "modelId"]
            templates:
              - condition:
                  contains:
                    kubernetes.annotations.isModel: "true"
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*.log
                    processors:
                      - add_kubernetes_metadata:
                          host: ${NODE_NAME}
                          matchers:
                            - logs_path:
                                logs_path: "/var/log/containers/"

      # output.elasticsearch:
        # host: '${NODE_NAME}'
        # hosts: '["http://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}"]'
      output.logstash:
        hosts: ['logstash-logstash:5044']
